language: java
jdk:
 - openjdk8
 - openjdk11

services: postgresql

before_script:
  - psql -c 'CREATE ROLE banks_fetch_user LOGIN; ALTER USER banks_fetch_user WITH SUPERUSER;' -U postgres
before_install:
  - "test x\"$TRAVIS_POSTGRESQL_VERSION\" = x\"\" || (sudo service postgresql stop && sudo service postgresql start $TRAVIS_POSTGRESQL_VERSION)"

script:
  - mvn clean verify
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
